$(document).ready(function() {
  var _that = this;
  var selectedIndex, inputField;
  /**
   * Describe this function...
   */
  function initialize() {
    return new Promise(function(resolve, reject) {
      // Block#: |jD7iV=qQ4YzKsHF+|8]
      com.fc.JavaScriptDistLib.GridView.saveTemplateCell('RadioGrid');
      com.fc.JavaScriptDistLib.GridView.removeAllCells('RadioGrid');
      on_gridview_length_configured_RadioGrid();
    });
  }
  /**
   * Describe this function...
   */
  function setByFields(fields) {
    return new Promise(function(resolve, reject) {
    });
  }
  /**
   * Describe this function...
   */
  function getCellNums() {
    // Block#: RhTAp@4yWO6ZP6)%gIen
    if(_that.inputField == null) {
      return 0;
    }
    return 10;
  }
  // Block#: Wh9JxP]+F9!Y`8:W).;%
  function on_Button_click(e) {
    try {
      // Block#: TLL}eJtx6dv0S|P:?0$Q
      initialize().then(response => {;
      });
      e.stopPropagation();
    } catch(e) {
      com.fc.JavaScriptDistLib.handleExceptionNative(e);
    }
  };
  $('[obj-name="Button"]').on('click', on_Button_click);
  // Block#: pxWn{txz74K:{f*A1?e;
  function on_gridview_length_configured_RadioGrid() {
    try {
      com.fc.JavaScriptDistLib.GridView.configureCells('RadioGrid', 10);
      $('[obj-name="RadioGrid"]').children().each(function(i) {
        if(i >= 0) {
          com.fc.JavaScriptDistLib.GridView.setContext($(this));
          com.fc.JavaScriptDistLib.GridView.executeConfigCallback('RadioGrid', $(this), i);
          com.fc.JavaScriptDistLib.GridView.resetContext($(this));
        }
      });
    } catch(e) {
      com.fc.JavaScriptDistLib.handleExceptionNative(e);
    }
  };
  // Block#: 0UM(dc%Sg~nRkNz9+t?|
  function on_gridview_cell_configured_RadioGridCell(RadioGridCell, number) {
    try {
      // Block#: |P1d2OZ(#8A$%^%$d7W3
      com.fc.JavaScriptDistLib.Label.setProperty["Text"]("RadioIndex", (com.fc.JavaScriptDistLib.TextLib.convertToText(number))); // Block#: s1(XqVG*C#}S[gnMz/#D
      if(number == _that.selectedIndex) {
        // Block#: s9xGM3xjsE14mSu$LEE|
        com.fc.JavaScriptDistLib.Image.setProperty["Image"]("RadioCircle", (com.fc.JavaScriptDistLib.ImageLibrary.createImageFromResource("https://develop.snapp.click/api/v2/raws/projects/resources/37f7cb06-cb73-487e-ab2a-9cee208c1396")));
      } else {
        // Block#: D3PS[a3om)Q6DMo_`kEq
        com.fc.JavaScriptDistLib.Image.setProperty["Image"]("RadioCircle", (com.fc.JavaScriptDistLib.ImageLibrary.createImageFromResource("https://develop.snapp.click/api/v2/raws/projects/resources/b8cb2e76-2af1-4645-8d9b-4b52976cb32f")));
      }
    } catch(e) {
      com.fc.JavaScriptDistLib.handleExceptionNative(e);
    }
  };
  com.fc.JavaScriptDistLib.GridView.setConfigCallback('RadioGridCell', on_gridview_cell_configured_RadioGridCell);
  // Block#: 6yIl@rm$+I(Y!u_TzKJh
  function on_gridview_cell_clicked_RadioGridCell(RadioGridCell, number) {
    try {
      // Block#: 5;|QK`21AzwlstZ]~l}s
      _that.selectedIndex = number;
      // Block#: WFqt*8I%u/c-alu*cyTu
      com.fc.JavaScriptDistLib.GridView.saveTemplateCell('RadioGrid');
      com.fc.JavaScriptDistLib.GridView.removeAllCells('RadioGrid');
      on_gridview_length_configured_RadioGrid();
    } catch(e) {
      com.fc.JavaScriptDistLib.handleExceptionNative(e);
    }
  }
  com.fc.JavaScriptDistLib.GridView.setClickCallback('RadioGridCell', on_gridview_cell_clicked_RadioGridCell);
  $('[obj-name="MainScreen"]').show();
});
// Generated by snapp
// 8192-133589-986448-18791
